[project]

site_name = "Erwartung - Data Unit Tests for the Energy Domain"
site_description = """Erwartung is an open-source repository that collects data unit tests for the energy domain. 
It uses LinkML to export these tests to different formats, so that they can be used in your datahub.
"""
site_author = "FlorianK13"
#site_url = "https://www.example.com/"
copyright = """
Copyright &copy; 2025 <a href="https://www.offis.de">OFFIS e.V.</a>  | <a href="https://www.offis.de/en/legals.html">Legals</a> 
"""
repo_url = "https://github.com/OFFIS-DIP/erwartung"
nav = [
    { "Home" = "index.md" },
    { "Data Unit Tests" = "unit-tests.md" },
    {"Exporters" = [
        "exporters/index.md", 
        {"Shape Constraint Language (SHACL)" = "exporters/shacl.md"},
        {"SQL Exporter" = "exporters/sql.md"},
    ]},
    {"Integrations" = [
        "integrations/index.md", 
        {"Graph Data" = "integrations/graph-data.md"},
        {"Relational Databases" = "integrations/relational-data.md"},
        {"Python" = "integrations/python.md"},
    ]},
    { "FAQ" = "faq.md" }
]


[project.theme]
custom_dir = "overrides"
language = "en"
font = false # Doesn't use Google Fonts with this command

features = [
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
#    "content.footnote.tooltips",
#    "content.tabs.link",
#    "content.tooltips",
#    "navigation.footer",
#    "navigation.indexes",
#    "navigation.instant",
#    "navigation.instant.prefetch",
#    "navigation.path",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]

