[project]

site_name = "Erwartung - Data Unit Tests for the Energy Domain"
site_description = """Erwartung is an open-source repository that collects data unit tests for the energy domain. 
It uses linkml to export these tests to different formats, so that they can be used in your datahub.
"""
site_author = "FlorianK13"
#site_url = "https://www.example.com/"
copyright = """
Copyright &copy; 2025 <a href="https://www.offis.de">OFFIS e.V.</a>  | <a href="https://www.offis.de/en/legals.html">Legals</a> 
"""
repo_url = "https://github.com/FlorianK13/erwartung"



[project.theme]

language = "en"

features = [
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
#    "content.footnote.tooltips",
#    "content.tabs.link",
#    "content.tooltips",
#    "navigation.footer",
#    "navigation.indexes",
#    "navigation.instant",
#    "navigation.instant.prefetch",
#    "navigation.path",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
